server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/energycommunities
spring.datasource.username=disysuser
spring.datasource.password=disyspw
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.serialization.write-dates-as-timestamps=false

#ist wie .env und next.config.js in einem File