server.port=8080
# TODO: delete comments for final submission, right now the db is not needed because we only work with example data
#spring.datasource.url=jdbc:postgresql://localhost:5432/energycommunities
#spring.datasource.username=disysuser
#spring.datasource.password=disyspw
#spring.datasource.driver-class-name=org.postgresql.Driver
# TODO: delete this line for final submission, just here for not trying to connect to postgres
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
